//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centro_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int Id { get; set; }
        public int SocioId { get; set; }
        public int ActividadId { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Actividades Actividades { get; set; }
        public virtual Socios Socios { get; set; }
    }
}
